name: example
description: raylib dart examples.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  raylib:
    path: ../
  intl: ^0.19.0

dev_dependencies:
  very_good_analysis: ^6.0.0
