name: raylib
description: raylib is a simple and easy-to-use library to enjoy videogames programming.
version: 0.2.0+1
homepage: https://gitlab.com/wolfenrain/dart-raylib

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  ffigen: ^4.1.2
  test: ^1.16.0
  very_good_analysis: ^2.4.0

ffigen:
  name: Raylib
  description: Bindings to Raylib
  output: lib/src/generated_bindings.dart
  llvm-path:
    - /usr/lib/llvm-12
  comments:
    style: any
    length: full
  headers:
    entry-points:
      - vendor/raylib/src/raylib.h
  enums:
    member-rename:
      '(.*)': 
          'KEY_(.*)': '$1'
          'GESTURE_(.*)': '$1'
          'MOUSE_BUTTON_(.*)': '$1'
          'CAMERA_(.*)': '$1'
          'BLEND_(.*)': '$1'
          'GAMEPAD_AXIS_(.*)': '$1'
          'GAMEPAD_BUTTON_(.*)': '$1'
